Error Response
jamespb20/CS4337-Project-Group9 pull request #17
Opened 2024-11-20 22:44 UTC by Drickido77

2024-11-27 15:14 UTC, CraigPhayer requested changes
The change in UserService on updateUser return type isnt needed so it can be changed back to void and you dont need to return anything

2024-11-27 18:50 UTC, Drickido77 commented
> The change in UserService on updateUser return type isnt needed so it can be changed back to void and you dont need to return anything

should be changed back to void now, sorry for late response

2024-11-27 19:11 UTC, CraigPhayer approved these changes

2024-11-29 18:00 UTC, brian6466 approved these changes

2024-12-02 00:08 UTC, merged

2024-12-02 00:08 UTC, Drickido77 commented
error responses approved